-- Department Budget Analysis for Layoff Planning 
SELECT c.CUSTOMER_NAME, COUNT(l.COMPANY_ID) AS TOTAL_COMPANIES
FROM CUSTOMER c
JOIN CUSTOMER_COMPANY_LINK l ON c.CUSTOMER_ID = l.CUSTOMER_ID
GROUP BY c.CUSTOMER_NAME
HAVING COUNT(l.COMPANY_ID) > 1
ORDER BY TOTAL_COMPANIES DESC;

-- Profit by department
SELECT d.DEPARTMENT_ID AS ID,
       COALESCE(d.DEPARTMENT_NAME, 'N/A')                AS DEPARTMENT_NAME,
       NVL(d.BUDGET,0)                                   AS DEPARTMENT_BUDGET,
       NVL(s.total_sales,0)                              AS TOTAL_SALES_AMOUNT,
       NVL(s.total_sales,0) - NVL(d.BUDGET,0)            AS REVENUE
FROM DEPARTMENT d
LEFT JOIN (
  SELECT dept_id, SUM(total_amount) AS total_sales
  FROM (
    SELECT DISTINCT e.DEPARTMENT_ID AS dept_id,
                    so.SALES_ORDER_ID,
                    so.TOTAL_AMOUNT
    FROM EMPLOYEE e
    JOIN SO_PARTNER_LINK spl ON spl.EMPLOYEE_ID = e.EMPLOYEE_ID
    JOIN SALES_ORDER so ON so.SALES_ORDER_ID = spl.SALES_ORDER_ID
    WHERE LOWER(NVL(spl.PARTNER_ROLE,' ')) = 'sales rep'
  ) x
  GROUP BY dept_id
) s ON s.dept_id = d.DEPARTMENT_ID
ORDER BY d.COMPANY_ID, d.DEPARTMENT_ID;

-- Manager Candidates For Departments
SELECT d.DEPARTMENT_ID,
       d.DEPARTMENT_NAME,
       e.EMPLOYEE_ID,
       e.FIRST_NAME || ' ' || e.LAST_NAME AS EMPLOYEE_FULL_NAME,
       jp.JOB_DESCRIPTION
FROM DEPARTMENT d
JOIN EMPLOYEE e ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN JOB_POSITION jp ON e.JOB_POSITION_ID = jp.JOB_POSITION_ID
WHERE LOWER(NVL(jp.JOB_DESCRIPTION,' ')) LIKE '%manage%'
ORDER BY d.COMPANY_ID, d.DEPARTMENT_ID, e.EMPLOYEE_ID;

-- Warehouse Inventory Cost Analysis
SELECT d.DEPARTMENT_ID,
       COALESCE(d.DEPARTMENT_NAME,'N/A')                     AS DEPARTMENT_NAME,
       NVL(d.BUDGET,0)                                       AS DEPARTMENT_BUDGET,
       SUM(NVL(i.QUANTITY_ON_HAND,0) * NVL(i.COST_PER_UNIT,0)) AS TOTAL_INVENTORY_COST,
       CASE 
         WHEN NVL(d.BUDGET,0) > 0 
         THEN ROUND(SUM(NVL(i.QUANTITY_ON_HAND,0) * NVL(i.COST_PER_UNIT,0)) / d.BUDGET * 100, 2)
         ELSE NULL
       END                                                   AS PERCENT_OF_BUDGET
FROM INVENTORY i
JOIN WAREHOUSE w ON i.WAREHOUSE_ID = w.WAREHOUSE_ID
JOIN DEPARTMENT d ON w.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_ID, d.DEPARTMENT_NAME, d.COMPANY_ID, d.BUDGET
HAVING SUM(NVL(i.QUANTITY_ON_HAND,0) * NVL(i.COST_PER_UNIT,0)) > 0
ORDER BY d.COMPANY_ID, d.DEPARTMENT_ID;

-- Analyzing Pending Orders and Sales Role Effectiveness 
SELECT * FROM SALES_ORDER WHERE SALES_ORDER_ID = 4;

SELECT spl.PARTNER_ROLE,
       e.EMPLOYEE_ID,
       e.FIRST_NAME || ' ' || e.LAST_NAME AS EMPLOYEE_FULL_NAME,
       e.JOB_POSITION_ID,
       jp.POSITION_TITLE AS JOB_POSITION_NAME
FROM SO_PARTNER_LINK spl
JOIN EMPLOYEE e ON spl.EMPLOYEE_ID = e.EMPLOYEE_ID
LEFT JOIN JOB_POSITION jp ON e.JOB_POSITION_ID = jp.JOB_POSITION_ID
WHERE spl.SALES_ORDER_ID = 4;

-- Enhancing ERP Transparency Through Customer–Vendor Linkage  
SELECT
  cust.CUSTOMER_NAME,
  cust.COMPANY_ID                                    AS CUSTOMER_ID,
  ccl.COMPANY_ID                                     AS VENDOR_ID,
  linked.COMPANY_NAME                                AS VENDOR_NAME,
  CASE WHEN ccl.CUSTOMER_ID IS NOT NULL THEN 'YES' ELSE 'NO' END
                                                     AS HAS_CUSTOMER_COMPANY_LINK,
  CASE WHEN EXISTS (
    SELECT 1 FROM VENDOR v
    WHERE v.COMPANY_ID = buyer.COMPANY_ID
      AND v.VENDOR_NAME = linked.COMPANY_NAME
  ) THEN 'YES' ELSE 'NO' END                          AS LINKED_NAME_IN_BUYER_VENDOR_LIST
FROM CUSTOMER cust
LEFT JOIN CUSTOMER_COMPANY_LINK ccl
  ON ccl.CUSTOMER_ID = cust.CUSTOMER_ID
  AND ccl.COMPANY_ID = 8          
LEFT JOIN COMPANY buyer
  ON buyer.COMPANY_ID = cust.COMPANY_ID
LEFT JOIN COMPANY linked
  ON linked.COMPANY_ID = ccl.COMPANY_ID
WHERE cust.CUSTOMER_ID = 5; 

-- Analyzing Procurement Risks (Missing Supplier Contracts)
SELECT v.VENDOR_ID,
       v.VENDOR_NAME,
       v.COMPANY_ID                            AS COMPANY_ID,
       vc.COMPANY_NAME                         AS COMPANY_NAME,
       CASE
        WHEN sc.CONTRACT_STATUS = 'Active' THEN 'YES'
        ELSE 'NO'
       END                                   AS HAS_ACTIVE_CONTRACT
FROM VENDOR v
LEFT JOIN COMPANY vc ON vc.COMPANY_ID = v.COMPANY_ID
LEFT JOIN SUPPLIER_CONTRACT sc
  ON sc.VENDOR_ID = v.VENDOR_ID
 AND sc.COMPANY_ID = vc.COMPANY_ID;

 -- Checking Sales Order Items Stock
SELECT sol.PRODUCT_ID,
       NVL(p.PRODUCT_NAME,'(no name)')            AS PRODUCT_NAME,
       sol.QUANTITY_ORDERED                        AS QTY_REQUIRED,
       NVL(inv.TOTAL_ON_HAND,0)                    AS QTY_ON_HAND,
       NVL(inv.TOTAL_ON_HAND,0) - sol.QUANTITY_ORDERED AS QTY_DIFF,
       CASE WHEN NVL(inv.TOTAL_ON_HAND,0) >= sol.QUANTITY_ORDERED THEN 'OK' ELSE 'SHORT' END AS STATUS
FROM SALES_ORDER_LINE sol
LEFT JOIN (
  SELECT PRODUCT_ID, SUM(NVL(QUANTITY_ON_HAND,0)) AS TOTAL_ON_HAND
  FROM INVENTORY
  GROUP BY PRODUCT_ID
) inv ON inv.PRODUCT_ID = sol.PRODUCT_ID
LEFT JOIN PRODUCT p ON p.PRODUCT_ID = sol.PRODUCT_ID
WHERE sol.SALES_ORDER_ID = 1
ORDER BY sol.PRODUCT_ID;

-- Analyzing Best Sold Product Categories
SELECT REVENUE_RNK,
       PRODUCT_CATEGORY_ID,
       CATEGORY_NAME,
       TOTAL_QTY,
       TOTAL_REVENUE
FROM (
  SELECT pc.PRODUCT_CATEGORY_ID,
         pc.CATEGORY_NAME,
         SUM(sol.QUANTITY_ORDERED)                                  AS TOTAL_QTY,
         SUM(sol.QUANTITY_ORDERED * NVL(sol.UNIT_PRICE,0))          AS TOTAL_REVENUE,
         RANK() OVER (ORDER BY SUM(sol.QUANTITY_ORDERED * NVL(sol.UNIT_PRICE,0)) DESC)      AS REVENUE_RNK
  FROM SALES_ORDER_LINE sol
  JOIN PRODUCT p ON p.PRODUCT_ID = sol.PRODUCT_ID
  LEFT JOIN PRODUCT_CATEGORY pc ON pc.PRODUCT_CATEGORY_ID = p.PRODUCT_CATEGORY_ID
  GROUP BY pc.PRODUCT_CATEGORY_ID, pc.CATEGORY_NAME
) ORDER BY REVENUE_RNK;

-- Misaligned Paymenats and Invoices
SELECT i.INVOICE_ID,
       i.INVOICE_NUMBER,
       i.TOTAL_AMOUNT                           AS INVOICE_TOTAL,
       NVL(SUM(p.PAYMENT_AMOUNT),0)             AS SUM_PAYMENT_AMOUNT,
       NVL(SUM(p.PAYMENT_AMOUNT),0) - NVL(SUM(l.AMOUNT_APPLIED),0) AS DIFF_PAYMENTS_MINUS_APPLIED
FROM INVOICE i
LEFT JOIN INVOICE_PAYMENT_LINK l ON l.INVOICE_ID = i.INVOICE_ID
LEFT JOIN PAYMENT p ON p.PAYMENT_ID = l.PAYMENT_ID
GROUP BY i.INVOICE_ID, i.INVOICE_NUMBER, i.TOTAL_AMOUNT
HAVING NOT NVL(SUM(p.PAYMENT_AMOUNT),0) = NVL(SUM(l.AMOUNT_APPLIED),0)
ORDER BY i.INVOICE_ID;

-- Analyzing Common Customers Between Companies
SELECT COMPANY_NAME FROM COMPANY WHERE COMPANY_ID IN (1,5);
SELECT ccl1.COMPANY_ID AS COMPANY_ID_1,
       ccl2.COMPANY_ID AS COMPANY_ID_2,
       ccl1.CUSTOMER_ID
FROM CUSTOMER_COMPANY_LINK ccl1
JOIN CUSTOMER_COMPANY_LINK ccl2
  ON ccl1.CUSTOMER_ID = ccl2.CUSTOMER_ID
 AND ccl1.COMPANY_ID < ccl2.COMPANY_ID
WHERE ccl1.COMPANY_ID IN (5,1) AND ccl2.COMPANY_ID IN (5,1)
ORDER BY ccl1.COMPANY_ID, ccl1.CUSTOMER_ID;