SELECT COUNT(*) AS TOTAL_COMPANIES FROM COMPANY;

SELECT COMPANY_ID,COMPANY_NAME, ADDRESS, POSTAL_CODE 
FROM COMPANY
WHERE POSTAL_CODE like 'M%';

SELECT * FROM DEPARTMENT;

SELECT COMPANY_ID, COUNT(*) as TOTAL_DEPARTMENTS 
FROM DEPARTMENT 
GROUP BY COMPANY_ID 
ORDER BY COMPANY_ID;

SELECT * FROM EMPLOYEE;

SELECT * FROM COMPANY WHERE COMPANY_ID = 3;

SELECT COUNT(*) AS TOTAL_EMPLOYEES 
FROM EMPLOYEE
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID FROM DEPARTMENT WHERE COMPANY_ID = 3
);

SELECT * FROM JOB_POSITION WHERE LOWER(JOB_DESCRIPTION) LIKE '%manage%';

SELECT * FROM CUSTOMER;
SELECT * FROM CUSTOMER_COMPANY_LINK;
SELECT * FROM COMPANY;

SELECT c.*
FROM CUSTOMER_COMPANY_LINK  ccl
JOIN CUSTOMER c ON ccl.CUSTOMER_ID = c.CUSTOMER_ID
WHERE ccl.COMPANY_ID = 1;

SELECT c.*
FROM CUSTOMER_COMPANY_LINK  ccl
JOIN COMPANY c ON ccl.COMPANY_ID = c.COMPANY_ID
WHERE ccl.CUSTOMER_ID = 13;

SELECT * FROM SALES_ORDER
WHERE EXTRACT(YEAR FROM REQUIRED_DATE) = 2025
  AND EXTRACT(MONTH FROM REQUIRED_DATE) = 11;

SELECT SALES_ORDER_ID, ORDER_NUMBER, TOTAL_AMOUNT FROM SALES_ORDER WHERE SALES_ORDER_ID = 1;

SELECT SALES_ORDER_ID, UNIT_PRICE, QUANTITY_ORDERED, LINE_TOTAL FROM SALES_ORDER_LINE
WHERE SALES_ORDER_ID = 1;

SELECT SALES_ORDER_ID, ORDER_NUMBER, ORDER_STATUS, TOTAL_AMOUNT, PAYMENT_STATUS FROM SALES_ORDER WHERE SALES_ORDER_ID = 1;
SELECT INVOICE_ID, INVOICE_NUMBER, SALES_ORDER_ID, SUB_TOTAL, TAX_AMOUNT, TOTAL_AMOUNT, INVOICE_STATUS FROM INVOICE WHERE SALES_ORDER_ID = 1;
SELECT PAYMENT_ID, PAYMENT_AMOUNT, PAYMENT_STATUS FROM PAYMENT WHERE PAYMENT_ID = 1;
SELECT * FROM INVOICE_PAYMENT_LINK WHERE INVOICE_ID = 1 OR PAYMENT_ID = 1;

SELECT count(e.EMPLOYEE_ID) as TOTAL_EMPLOYEES, sum(e.SALARY) as TOTAL_SALARY, d.BUDGET, d.DEPARTMENT_ID
FROM EMPLOYEE e
LEFT JOIN DEPARTMENT d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_ID, d.BUDGET
HAVING sum(e.SALARY) > d.BUDGET;


SELECT PRODUCT_CATEGORY_ID,
       COUNT(*) OVER (PARTITION BY PRODUCT_CATEGORY_ID) AS PRODUCTS_IN_CATEGORY,
       PRODUCT_ID,
       PRODUCT_NAME
FROM PRODUCT
ORDER BY PRODUCT_CATEGORY_ID, PRODUCT_ID;

SELECT * FROM PRODUCT_CATEGORY;

SELECT * FROM BILL_OF_MATERIAL WHERE PRODUCT_ID = 4;

SELECT * FROM MATERIAL WHERE MATERIAL_ID IN (SELECT MATERIAL_ID FROM BILL_OF_MATERIAL WHERE PRODUCT_ID = 4);

SELECT * FROM PURCHASE_ORDER_LINE WHERE MATERIAL_ID IN (SELECT MATERIAL_ID FROM BILL_OF_MATERIAL WHERE PRODUCT_ID = 4);

SELECT PURCHASE_ORDER_ID, PURCHASE_ORDER_NUMBER, TOTAL_AMOUNT FROM PURCHASE_ORDER WHERE PURCHASE_ORDER_ID = 2;

SELECT PURCHASE_ORDER_ID, UNIT_COST, QUANTITY_ORDERED, LINE_TOTAL FROM PURCHASE_ORDER_LINE
WHERE PURCHASE_ORDER_ID = 2;

SELECT * FROM VENDOR WHERE COMPANY_ID = (SELECT COMPANY_ID FROM COMPANY WHERE COMPANY_NAME = 'Regional Furniture Co.'
);

SELECT *
FROM SUPPLIER_CONTRACT
WHERE START_DATE IS NOT NULL
  AND END_DATE   IS NOT NULL
  AND END_DATE >= ADD_MONTHS(START_DATE, 12);

SELECT WAREHOUSE_ID, WAREHOUSE_NAME, LOCATION, POSTAL_CODE, STORAGE_CAPACITY, DEPARTMENT_ID, MANAGER_ID FROM WAREHOUSE ORDER BY STORAGE_CAPACITY;

SELECT INVENTORY_ID, WAREHOUSE_ID, PRODUCT_ID, QUANTITY_RESERVED, QUANTITY_AVAILABLE, COST_PER_UNIT FROM INVENTORY WHERE COST_PER_UNIT < 100;

