CREATE VIEW vw_sales_order_summary AS
SELECT so.SALES_ORDER_ID,
       so.ORDER_NUMBER,
       so.ORDER_DATE,
       so.REQUIRED_DATE,
       so.ORDER_STATUS,
       so.PAYMENT_STATUS,
       so.TOTAL_AMOUNT,
       COUNT(sol.SALES_ORDER_ID)                      AS LINE_COUNT,
       NVL(SUM(sol.LINE_TOTAL),0)                     AS LINES_SUBTOTAL,
       so.TOTAL_AMOUNT - NVL(SUM(sol.LINE_TOTAL),0)   AS TOTAL_DIFF
FROM SALES_ORDER so
LEFT JOIN SALES_ORDER_LINE sol ON sol.SALES_ORDER_ID = so.SALES_ORDER_ID
GROUP BY so.SALES_ORDER_ID,
         so.ORDER_NUMBER,
         so.ORDER_DATE,
         so.REQUIRED_DATE,
         so.ORDER_STATUS,
         so.PAYMENT_STATUS,
         so.TOTAL_AMOUNT;

SELECT SALES_ORDER_ID AS ID, ORDER_NUMBER, TOTAL_AMOUNT, LINE_COUNT, LINES_SUBTOTAL, TOTAL_DIFF FROM VW_SALES_ORDER_SUMMARY;

CREATE OR REPLACE VIEW vw_sales_order_detail AS
SELECT so.SALES_ORDER_ID,
       so.ORDER_NUMBER,
       so.ORDER_DATE,
       so.REQUIRED_DATE,
       so.ORDER_STATUS,
       so.PAYMENT_STATUS,
       sol.UNIT_PRICE,
       sol.QUANTITY_ORDERED,
       sol.LINE_TOTAL,
       sol.PRODUCT_ID,
       p.PRODUCT_NAME
FROM SALES_ORDER so
JOIN SALES_ORDER_LINE sol ON sol.SALES_ORDER_ID = so.SALES_ORDER_ID
LEFT JOIN PRODUCT p ON p.PRODUCT_ID = sol.PRODUCT_ID;

SELECT ORDER_NUMBER, UNIT_PRICE, QUANTITY_ORDERED, LINE_TOTAL, PRODUCT_NAME FROM vw_sales_order_detail;

CREATE VIEW vw_purchase_order_summary AS
SELECT po.PURCHASE_ORDER_ID,
       po.PURCHASE_ORDER_NUMBER,
       po.ORDER_DATE,
       po.TOTAL_AMOUNT,
       COUNT(pol.PURCHASE_ORDER_ID)                      AS LINE_COUNT,
       NVL(SUM(pol.LINE_TOTAL),0)                        AS LINES_SUBTOTAL,
       po.TOTAL_AMOUNT - NVL(SUM(pol.LINE_TOTAL),0)      AS TOTAL_DIFF
FROM PURCHASE_ORDER po
LEFT JOIN PURCHASE_ORDER_LINE pol ON pol.PURCHASE_ORDER_ID = po.PURCHASE_ORDER_ID
GROUP BY po.PURCHASE_ORDER_ID,
         po.PURCHASE_ORDER_NUMBER,
         po.ORDER_DATE,
         po.TOTAL_AMOUNT;

SELECT PURCHASE_ORDER_ID AS ID, PURCHASE_ORDER_NUMBER AS ORDER_NUMBER, TOTAL_AMOUNT, LINE_COUNT, LINES_SUBTOTAL, TOTAL_DIFF FROM vw_purchase_order_summary;

CREATE OR REPLACE VIEW vw_purchase_order_detail AS
SELECT po.PURCHASE_ORDER_ID,
       po.PURCHASE_ORDER_NUMBER,
       pol.UNIT_COST,
       pol.QUANTITY_ORDERED,
       pol.LINE_TOTAL,
       pol.MATERIAL_ID,
       m.MATERIAL_NAME
FROM PURCHASE_ORDER po
JOIN PURCHASE_ORDER_LINE pol ON pol.PURCHASE_ORDER_ID = po.PURCHASE_ORDER_ID
LEFT JOIN MATERIAL m ON m.MATERIAL_ID = pol.MATERIAL_ID;

SELECT PURCHASE_ORDER_NUMBER, UNIT_COST, QUANTITY_ORDERED, LINE_TOTAL, MATERIAL_NAME FROM vw_purchase_order_detail;